/* The book: four tabs, their sections, and how each dish is served. */
const CHAPTERS = [
  { n: 1, name: 'Pasta & nudlar', short: 'Pasta', color: '#d9573b', sections: [
    ['Tomat', ['linsbolognese', 'vegansk-bolognese', 'napolitana', 'puttanesca', 'norma', 'rakpasta']],
    ['Krämigt', ['carbonara', 'kramig-pastasas', 'pastasas-mor', 'svamppasta', 'avokadopasta', 'zucchinipasta', 'dillpasta', 'gnocchi', 'stuvade-makaroner']],
    ['Kall pasta & dressing', ['paprika-chorizo', 'pastasallad']],
    ['Nudlar', ['ramen', 'stekta-nudlar']]] },
  { n: 2, name: 'Grytor, soppor & varmrätter', short: 'Grytor', color: '#e0a23a', sections: [
    ['Grytor', ['chili-sin-carne', 'bonchili', 'korv-stroganoff', 'linsgryta', 'kikartsgryta', 'filegryta', 'viltgryta']],
    ['Soppor', ['artsoppa', 'minestrone', 'broccolisoppa', 'morotssoppa', 'purjolokssoppa', 'vegofarssoppa']],
    ['Ugn, panna & ris', ['vegobullar', 'pannbiff', 'vegoburgare', 'fyllda-paprikor', 'hoisin-filebitar', 'yakiniku', 'svartbonsas', 'bowl', 'raggmunkar', 'ugnspannkaka']]] },
  { n: 3, name: 'Såser, röror & tillbehör', short: 'Såser', color: '#86ad58', sections: [
    ['Varma såser', ['brunsas', 'loksas', 'graddsas', 'currysas', 'jordnotssas']],
    ['Kalla såser', ['kall-vitlokssas', 'kall-ort-vitlokssas', 'kall-pestosas', 'ranchdressing', 'remouladsas', 'dillsas', 'dill-kaprissas', 'avokadosas', 'tzatziki']],
    ['Dipp & röror', ['hummus', 'bonblandning', 'skagenrora', 'varrullesaser']],
    ['Sallader & inlagt', ['kalsallad', 'farskpotatissallad', 'gurk-tomatsallad', 'asiatisk-gurka', 'pressgurka', 'picklad-rodlok']],
    ['Tillbehör', ['potatismos', 'gult-ris', 'stekt-tofu', 'timjan-tofu']]] },
  { n: 4, name: 'Frukost, bakat & sött', short: 'Sött', color: '#7d9ad8', sections: [
    ['Frukost', ['overnight-oats', 'chiapudding', 'bananpannkakor', 'scrambled-tofu', 'avokadotoast', 'bruschetta', 'fattiga-riddare']],
    ['Bakat', ['bananbrod', 'bullar', 'muffins', 'mordegskakor', 'sockerkaka', 'kladdkaka', 'mug-cake']],
    ['Pajer', ['smulpaj', 'bananpaj']],
    ['Drycker', ['varm-choklad', 'dalgona', 'islatte']]] }
];
const CREAM = '#f2ead8';
const VIS = {
  /* 1 · Pasta */
  'linsbolognese': { v: 'pot', enamel: '#b8472e', inner: '#2a1f1b', counts: { bay: 2 } },
  'vegansk-bolognese': { v: 'pot' },
  'napolitana': { v: 'plate', m: 'nest', extra: ['spaghetti'], base: '#c43b22', glazes: ['white', 'oat', 'blue'] },
  'puttanesca': { v: 'plate', m: 'nest', glazes: ['white', 'celadon', 'ink'] },
  'norma': { v: 'plate', m: 'mound', bs: 'pool', dabs: 1, spread: 1.15, counts: { rigatoni: 42 }, glazes: ['white', 'butter', 'blue'] },
  'rakpasta': { v: 'plate', m: 'nest', glazes: ['ink', 'white', 'blue'] },
  'carbonara': { v: 'plate', m: 'nest', swap: { tofu: 'smokedtofu' }, glazes: ['ink', 'rust', 'sage'] },
  'kramig-pastasas': { v: 'plate', m: 'nest', extra: ['tagliatelle'], swap: { onion: 'shallot' }, glazes: ['ink', 'rust', 'sage', 'blue'] },
  'pastasas-mor': { v: 'plate', m: 'nest', extra: ['spaghetti'], glazes: ['ink', 'sage', 'rust'] },
  'svamppasta': { v: 'plate', m: 'nest', extra: ['tagliatelle'], glazes: ['ink', 'blue', 'rust'] },
  'avokadopasta': { v: 'plate', m: 'nest', blend: 1, blendKeep: .5, base: '#b3c768', glazes: ['white', 'oat', 'rust'] },
  'zucchinipasta': { v: 'plate', m: 'nest', glazes: ['ink', 'blue', 'rust'] },
  'dillpasta': { v: 'plate', m: 'nest', blend: 1, blendKeep: .5, glazes: ['white', 'oat', 'ink'] },
  'gnocchi': { v: 'skillet', m: 'fill', counts: { gnocchi: 26 } },
  'stuvade-makaroner': { v: 'pot', enamel: '#e6e0d2', inner: '#e8e2d4', m: 'fill', counts: { macaroni: 60 } },
  'paprika-chorizo': { v: 'plate', m: 'mound', nobase: 1, glazes: ['white', 'ink', 'celadon'] },
  'pastasallad': { v: 'bowl', m: 'mound', bs: 'dressing', spread: .9, counts: { farfalle: 30 }, glazes: ['white', 'blue', 'ink'] },
  'ramen': { v: 'bowl', m: 'sectors', bs: 'broth', base: '#9a5a2a', bulkS: .5, counts: { tofu: 6, garlic: 0, ginger: 0, spinach: 5, shiitake: 6, pakchoi: 3, edamame: 12 }, glazes: ['ink', 'white', 'rust'] },
  'stekta-nudlar': { v: 'plate', m: 'nest', base: '#8a5530', glazes: ['white', 'celadon', 'butter'] },
  /* 2 · Grytor & soppor */
  'chili-sin-carne': { v: 'pot' },
  'bonchili': { v: 'pot', enamel: '#2f4d6b', inner: '#231d1b' },
  'korv-stroganoff': { v: 'skillet', m: 'fill' },
  'linsgryta': { v: 'pot', enamel: '#d6c7a9', inner: '#2a2320' },
  'kikartsgryta': { v: 'pot', enamel: '#6b7a4a', inner: '#231d1b' },
  'filegryta': { v: 'pot' },
  'viltgryta': { v: 'pot', enamel: '#5b2b2b', inner: '#231d1b', counts: { jam: 4 } },
  'artsoppa': { v: 'bowl', bs: 'soup', blend: 1, blendKeep: .2, swirl: CREAM, glazes: ['white', 'oat', 'ink'] },
  'minestrone': { v: 'bowl', bs: 'broth', base: '#c0643a', dens: .8, glazes: ['white', 'oat', 'celadon'] },
  'broccolisoppa': { v: 'bowl', bs: 'soup', blend: 1, blendKeep: .15, swirl: CREAM, glazes: ['white', 'oat', 'rust'] },
  'morotssoppa': { v: 'bowl', bs: 'soup', blend: 1, blendKeep: 0, swirl: CREAM, glazes: ['ink', 'blue', 'white'] },
  'purjolokssoppa': { v: 'bowl', bs: 'soup', blend: 1, blendKeep: .1, hide: ['bacon'], glazes: ['ink', 'rust', 'blue'] },
  'vegofarssoppa': { v: 'bowl', bs: 'broth', base: '#b8552f', glazes: ['white', 'oat'] },
  'vegobullar': { v: 'skillet', m: 'fill', hide: ['mince'], form: { g: 'meatball', k: 'mince', n: 7, s: .085, col: '#7a4a2e', rr: .55 }, counts: { coriander: 18 } },
  'pannbiff': { v: 'plate', m: 'mound', nobase: 1, hide: ['mince'], form: { g: 'patty', k: 'mince', n: 4, s: .2, col: '#6e4027', rr: .5 }, counts: { onion: 6 }, glazes: ['white', 'oat', 'blue'] },
  'vegoburgare': { v: 'skillet', m: 'mound', nobase: 1, hide: ['mince'], form: { g: 'patty', k: 'mince', n: 4, s: .24, col: '#734528', rr: .5 }, counts: { onion: 0, garlic: 0, beet: 0 } },
  'fyllda-paprikor': { v: 'ovendish', w: .82, h: .6, glaze: 'white', m: 'mound', nobase: 1, hide: ['onion', 'garlic', 'mince', 'corn', 'melt', 'redpepper'], form: { g: 'stuffed', k: 'redpepper', n: 6, s: .21, col: '#d7342a' } },
  'hoisin-filebitar': { v: 'ovendish', w: .82, h: .62, glaze: 'white', m: 'fill', counts: { parsley: 16 } },
  'yakiniku': { v: 'bowl', m: 'mound', base: '#5a2d1a', swap: { filet: 'pulled' }, counts: { pulled: 16 }, glazes: ['white', 'oat', 'butter'] },
  'svartbonsas': { v: 'plate', m: 'mound', extra: ['rice'], bulkS: .34, bulkOff: [-.07, -.07], base: '#3a2a26', glazes: ['white', 'butter', 'oat'] },
  'bowl': { v: 'bowl', m: 'sectors', nobase: 1, bulkS: .55, swap: { carrot: 'carrotshred', avocado: 'avocado' }, counts: { vegpatty: 2, avocado: 5, carrotshred: 14, beet: 0, edamame: 16 }, deco: [{ g: 'dab', col: '#f4efe2', s: .12, n: 1, L: 4.5, spread: .05 }, { g: 'sesame', col: '#f0e2c0', s: .012, n: 20 }], glazes: ['ink', 'white', 'blue'] },
  'raggmunkar': { v: 'skillet', m: 'mound', nobase: 1, form: { g: 'raggmunk', k: 'potato', n: 3, s: .28, rr: .45 }, hide: ['potato'] },
  'ugnspannkaka': { v: 'ovendish', w: .8, h: .62, glaze: 'white', m: 'fill', base: '#e0a84e', bs: 'baked', swap: { leek: 'leek' }, counts: { smokedtofu: 12, leek: 10 } },
  /* 3 · Såser */
  'brunsas': { v: 'boat', glazes: ['white', 'oat', 'celadon'], R: .34, bs: 'sauce', base: '#7b4a2b' },
  'loksas': { v: 'boat', glazes: ['white', 'oat', 'celadon'], R: .34, base: '#b88a5a', swap: { onion: 'friedonion' }, counts: { friedonion: 22 } },
  'graddsas': { v: 'boat', glazes: ['white', 'oat', 'celadon'], R: .33, bs: 'soup', base: '#c9a27a', hide: ['jam', 'lingon'] },
  'currysas': { v: 'boat', glazes: ['white', 'oat', 'celadon'], R: .33, bs: 'soup', hide: ['garlic'] },
  'jordnotssas': { v: 'boat', glazes: ['white', 'oat', 'celadon'], R: .33, base: '#b27238', hide: ['onion', 'garlic'] },
  'kall-vitlokssas': { v: 'ramekin', R: .32, bs: 'soup', deco: [{ g: 'drizzle', col: '#c9a93a', s: .2, n: 2 }], counts: { garlic: 3 }, glazes: ['ink', 'blue', 'rust'] },
  'kall-ort-vitlokssas': { v: 'ramekin', R: .32, bs: 'soup', counts: { sundried: 6, garlic: 2 }, glazes: ['ink', 'rust', 'sage'] },
  'kall-pestosas': { v: 'ramekin', R: .32, bs: 'soup', counts: { pesto: 10 }, glazes: ['ink', 'rust'] },
  'ranchdressing': { v: 'ramekin', R: .32, bs: 'soup', counts: { garlic: 0, chiliflakes: 0 }, glazes: ['ink', 'blue', 'sage'] },
  'remouladsas': { v: 'ramekin', R: .32, bs: 'soup', counts: { relish: 18, caper: 10, dill: 4 }, glazes: ['ink', 'blue'] },
  'dillsas': { v: 'ramekin', R: .32, bs: 'soup', counts: { relish: 16, dill: 7 }, glazes: ['ink', 'rust', 'blue'] },
  'dill-kaprissas': { v: 'ramekin', R: .32, bs: 'soup', counts: { dill: 6, caper: 10, greenolive: 8 }, glazes: ['ink', 'rust'] },
  'avokadosas': { v: 'ramekin', R: .32, bs: 'soup', blend: 1, blendKeep: 0, counts: { garlic: 0, chive: 20, dill: 3, chili: 3 }, glazes: ['white', 'rust', 'oat'] },
  'tzatziki': { multi: 1, v: 'ramekin', bs: 'soup', slots: [{ x: .31, y: .35, R: .25 }, { x: .66, y: .64, R: .28 }], per: [{ counts: { carrotshred: 14, cucumber: 0, garlic: 0 }, swap: { cucumber: 'cucshred', carrot: 'carrotshred' }, base: '#f1ecdc' }, { swap: { cucumber: 'cucshred' }, counts: { cucshred: 16, garlic: 2 }, deco: [{ g: 'drizzle', col: '#bca23a', s: .2 }] }], glazes: ['ink', 'blue', 'sage'] },
  'hummus': { v: 'bowl', R: .36, bs: 'mash', blend: 1, blendKeep: .15, counts: { garlic: 0, chiliflakes: 0, lemon: 0 }, deco: [{ g: 'oildrop', col: '#c9a93a', s: .12, n: 1 }], glazes: ['ink', 'blue', 'rust'] },
  'bonblandning': { v: 'bowl', m: 'mound', nobase: 1, swap: { avocado: 'avocube' }, glazes: ['white', 'ink', 'rust'] },
  'skagenrora': { v: 'bowl', R: .36, bs: 'soup', swap: { avocado: 'avocube' }, counts: { roe: 3, tofu: 8 }, glazes: ['ink', 'blue'] },
  'varrullesaser': { multi: 1, v: 'ramekin', bs: 'soup', glazes: ['white', 'oat', 'celadon'], per: [{ bs: 'broth', base: '#6b3a1e' }, {}, {}] },
  'kalsallad': { v: 'bowl', m: 'mound', bs: 'dressing', spread: .85, counts: { cabbage: 100, sesame: 40 }, glazes: ['ink', 'rust', 'blue'] },
  'farskpotatissallad': { v: 'bowl', m: 'mound', bs: 'dressing', spread: .85, glazes: ['ink', 'blue', 'white'] },
  'gurk-tomatsallad': { v: 'bowl', m: 'mound', nobase: 1, glazes: ['white', 'ink', 'oat'] },
  'asiatisk-gurka': { v: 'plate', m: 'mound', nobase: 1, swap: { cucumber: 'cucumber' }, form: { g: 'accordion', k: 'cucumber', n: 5, s: .16, rr: .45 }, hide: ['cucumber', 'lime'], deco: [{ g: 'flakes', col: '#b72a18', s: .12, n: 3, spread: .6 }, { g: 'sesame', col: '#f0e2c0', s: .012, n: 24, spread: .6 }], glazes: ['white', 'ink', 'celadon'] },
  'pressgurka': { v: 'jar', R: .38, m: 'fill', base: '#e9efd3', bs: 'broth', counts: { cucumber: 22 } },
  'picklad-rodlok': { multi: 1, v: 'jar', m: 'fill', bs: 'broth', base: '#e2a2b8', swap: { redonion: 'redonion' }, per: [{ counts: { redonion: 14 } }, { counts: { redonion: 22 } }] },
  'potatismos': { v: 'bowl', bs: 'mash', blend: 1, blendAll: 1, blendKeep: 0, base: '#f1e2b0', deco: [{ g: 'butter', col: '#f4dc84', s: .09, n: 1, spread: .1 }], glazes: ['ink', 'blue', 'rust'] },
  'gult-ris': { v: 'bowl', m: 'mound', nobase: 1, swap: { rice: 'yellowrice', onion: 'friedonion' }, counts: { friedonion: 16, garlic: 0, clove: 3, bay: 1 }, glazes: ['ink', 'blue', 'white'] },
  'stekt-tofu': { v: 'skillet', m: 'mound', base: '#7a3c16', bs: 'pool', spread: .9, counts: { tofu: 16 }, deco: [{ g: 'dab', col: '#6a3417', s: .07, n: 7, spread: .8, L: 2.5 }, { g: 'citrus', col: '#86b83c', s: .1, n: 1, spread: .6, L: 5 }], swap: { lime: 'none', lemon: 'none' } },
  'timjan-tofu': { v: 'skillet', m: 'fill', counts: { tofu: 14 } },
  /* 4 · Frukost & sött */
  'overnight-oats': { multi: 1, v: 'jar', m: 'fill', bs: 'soup', counts: { oats: 26, chia: 2 } },
  'chiapudding': { v: 'jar', R: .34, m: 'fill', bs: 'soup', itemScale: .5, counts: { chia: 34 } },
  'bananpannkakor': { v: 'plate', m: 'mound', nobase: 1, hide: ['banana'], form: { g: 'pancakes', k: 'banana', n: 1, s: .5, L: 2 }, glazes: ['blue', 'ink', 'celadon'] },
  'scrambled-tofu': { v: 'skillet', m: 'mound', nobase: 1, swap: { tofu: 'tofucrumble' }, spread: 1 },
  'avokadotoast': { v: 'board', w: .78, h: .6, m: 'mound', nobase: 1, hide: ['avocado', 'spinach', 'cheeseslice', 'pesto'], form: { g: 'sandwich', k: 'bread', n: 1, s: .44, L: 2 } },
  'bruschetta': { v: 'board', w: .84, h: .64, m: 'mound', nobase: 1, hide: ['tomato', 'basil', 'garlic'], form: { g: 'toast', k: 'bread', n: 4, s: .24, v: { top: 'bruschetta', golden: 1 }, norot: 1 } },
  'fattiga-riddare': { v: 'plate', m: 'mound', nobase: 1, form: { g: 'toast', k: 'bread', n: 3, s: .26, v: { top: 'cinnamon', golden: 1 }, rr: .42 }, glazes: ['blue', 'ink', 'sage'] },
  'bananbrod': { v: 'board', w: .8, h: .56, m: 'mound', nobase: 1, hide: ['banana'], form: { g: 'loaf', k: 'banana', n: 1, s: .62, norot: 1 } },
  'bullar': { v: 'tray', w: .86, h: .7, m: 'mound', nobase: 1, hide: ['pearl', 'cinnamon', 'spice'], form: { g: 'bun', k: 'pearl', n: 9, s: .17, norot: 0 } },
  'muffins': { v: 'tray', w: .84, h: .6, m: 'mound', nobase: 1, form: { g: 'muffin', k: 'none', n: 6, s: .2 } },
  'mordegskakor': { v: 'tray', w: .86, h: .66, m: 'mound', nobase: 1, hide: ['lemon', 'poppy', 'jam'], form: { g: 'cookie', k: 'poppy', n: 12, s: .13 } },
  'sockerkaka': { v: 'plate', R: .44, m: 'mound', nobase: 1, hide: ['nuts'], form: { g: 'cake', k: 'nuts', n: 1, s: .6, v: { kind: 'tosca' } }, glazes: ['ink', 'blue', 'sage'] },
  'kladdkaka': { v: 'plate', R: .44, m: 'mound', nobase: 1, form: { g: 'cake', k: 'cocoa', n: 1, s: .6, v: { kind: 'kladd' } }, glazes: ['white', 'oat', 'celadon'] },
  'mug-cake': { v: 'mug', R: .3, m: 'mound', nobase: 1, form: { g: 'cake', k: 'cocoa', n: 1, s: .44, v: { kind: 'mug' } }, glazes: ['white', 'butter', 'celadon'] },
  'smulpaj': { v: 'piedish', R: .42, m: 'fill', base: '#b8404a', dens: .9, hide: ['cinnamon'], counts: { apple: 6, berries: 12 }, deco: [{ g: 'crumbletop', col: '#d9a860', s: .56, n: 1, spread: .05, L: 4 }], glazes: ['blue', 'white', 'sage'] },
  'bananpaj': { v: 'piedish', R: .42, m: 'fill', base: '#e2c27a', counts: { banana: 16 }, deco: [{ g: 'crumbletop', col: '#d49a4a', s: .5, n: 1, spread: .05, L: 4 }], glazes: ['ink', 'rust', 'sage'] },
  'varm-choklad': { v: 'mug', R: .31, bs: 'froth', glazes: ['white', 'rust', 'butter'] },
  'dalgona': { v: 'glass', R: .3, bs: 'soup', base: '#efe7da', form: { g: 'foam', k: 'coffee', n: 1, s: .38, col: '#c68a52', L: 5 }, counts: { ice: 2 } },
  'islatte': { v: 'glass', R: .3, bs: 'broth', base: '#b98a5c', counts: { ice: 5 } }
};
